### ISSUE TITLE
 air-quality-dashboard and covid-19-dashboard fail in deployment testing mode

### ISSUE THREAD

**Issue by chritter** [StatCan/R-dashboards#24]
Hello,
In the deployment testing setup I found that the R Shiny dashboard air-quality-dashboard and covid-19-dashboard are not working. All other examples work fine! I get the error
```
An error has occurred

The application failed to start.

The application exited during initialization.
```
The error logs indicate that the Minio bucket from which the data is retrieved is not available anymore.

**Comment by blairdrummond** [comment]
This is also related to #8 ; even if we remove the dashboard from the repo, it actually will still be running on the server.

**Comment by brendangadd** [comment]
Old dashboards removed by @blairdrummond. Thanks!
